#!/bin/sh

# PROVIDE: varnishncsa
# REQUIRE: DAEMON varnishd
# KEYWORD: shutdown

#
# Add the following line to /etc/rc.conf to enable varnishncsa:
#
# varnishncsa_syslog_enable="YES"
#
# Configuration variables and their default values:
#
# varnishncsa_syslog_pidfile - full path to the PID file.
#       default: "/var/run/varnishncsa_syslog.pid"
#
# varnishncsa_syslog_logformat - log file format.
#       default: "" (uses varnishncsa's default format)
#       example: "%h %l %u %t %r %s %b %{Referer}i %{User-agent}i"
#
# varnishncsa_syslog_query - VSL Query.
#       default: ""
#
# varnishncsa_syslog_flags - command line arguments.
#       default: "-t off -P ${varnishncsa_syslog_pidfile}\
#                 ${varnishncsa_syslog_logformat:+ -F \"$varnishncsa_syslog_logformat\"}
#                 ${varnishncsa_syslog_query:+ -q \"$varnishncsa_syslog_query\"}"
#
# varnishncsa_syslog_loggeropts - logger options.
#	default: "-p local6.info"
#
# See varnishncsa(1) for a detailed overview of command-line options.
#

. /etc/rc.subr

name=varnishncsa_syslog
rcvar=${name}_enable

load_rc_config ${name}

: ${varnishncsa_syslog_enable:=NO}
: ${varnishncsa_syslog_pidfile=/var/run/${name}.pid}
: ${varnishncsa_syslog_flags="-t off -P ${varnishncsa_syslog_pidfile}\
${varnishncsa_syslog_logformat:+ -F \"$varnishncsa_syslog_logformat\"}\
${varnishncsa_syslog_query:+ -q \"$varnishncsa_syslog_query\"}"}
: ${varnishncsa_syslog_loggeropts="-p local6.info"}

procname="/usr/local/bin/varnishncsa"
command="/usr/sbin/daemon"
command_args="-f -u varnishlog\
 sh -c '${procname} ${varnishncsa_syslog_flags} | logger ${varnishncsa_syslog_loggeropts}'"
pidfile=${varnishncsa_syslog_pidfile}
start_precmd=precmd

precmd()
{
        # $varnishncsa_flags gets applied too early if we don't do this.
        rc_flags=""

	if [ ! -e ${pidfile} ]; then
		install -o varnishlog -g varnish -m 644 /dev/null ${pidfile};
	fi
}

run_rc_command "$1"
