#!/bin/sh

# PROVIDE: varnishncsa
# REQUIRE: DAEMON varnishd
# KEYWORD: shutdown

#
# Link <id> to this file. E.g.
#
#       ln -s /usr/local/etc/rc.d/varnishncsa_syslog_vhost_ /usr/local/etc/rc.d/varnishncsa_syslog_vhost0
#
# Add the following line to /etc/rc.conf to enable varnishncsa:
#
# <id>_enable="YES"
#
# Configuration variables and their default values:
#
# <id>_pidfile - full path to the PID file.
#       default: "/var/run/<id>.pid"
#
# <id>_hostname - hostname.
#       default: "example.com"
#
# <id>_logformat - log file format.
#       default: "" (uses varnishncsa's default format)
#       example: "%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\""
#
# <id>_query - VSL Query.
#       default: "ReqHeader:Host ~ \\\"^${<id>_hostname}\$\\\""
#
# <id>_flags - command line arguments.
#       default: "-t off -P ${<id>_pidfile}\
#                 ${<id>_logformat:+ -F \"$<id>_logformat\"} -q \"${<id>_query}\""
#
# <id>_loggeropts - logger options.
#       default: "-p local6.info"
#
# See varnishncsa(1) for a detailed overview of command-line options.
#

. /etc/rc.subr

name=${0##*/}
rcvar=${name}_enable

load_rc_config ${name}

eval : '$'{${name}_enable:=NO}
eval : '$'{${name}_hostname=example.com}
eval vhost='$'{${name}_hostname}
eval : '$'{${name}_pidfile=/var/run/${name}.pid}
eval pidfile='$'{${name}_pidfile}
eval logformat='$'{${name}_logformat}
default_query="ReqHeader:Host ~ \\\"^${vhost}\$\\\""
eval : '$'{${name}_query='$'{default_query}}
eval query='$'{${name}_query}
default_flags="-t off -P ${pidfile} ${logformat:+ -F \"${logformat}\"} -q \"${query}\""
eval : '$'{${name}_flags='$'{default_flags}}
eval flags='$'{${name}_flags}
eval : '$'{${name}_loggeropts="-p local6.info"}
eval loggeropts='$'{${name}_loggeropts}

procname="/usr/local/bin/varnishncsa"
command="/usr/sbin/daemon"
command_args="-f -u varnishlog sh -c '${procname} ${flags} | logger ${loggeropts}'"
start_precmd=precmd

echo $command_args

precmd()
{
        # $varnishncsa_flags gets applied too early if we don't do this.
        rc_flags=""

	if [ ! -e ${pidfile} ]; then
		install -o varnishlog -g varnish -m 644 /dev/null ${pidfile};
	fi

	if [ ! -e ${logfile} ]; then
		install -o varnishlog -g varnish -m 640 /dev/null ${logfile};
	fi
}

run_rc_command "$1"
